config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'users#index', as: :unauthenticated_root
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:index] do
    resources :groups, only: %i[index show new create destroy] do
      resources :expenses, only: %i[index show new create destroy]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, user: user
    can :manage, Expense, user: user

    can %i[create read], Group
    can %i[create read], Expense
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :group

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :expenses, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true, length: { maximum: 250 }

  def total_expenses
    expenses.sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, foreign_key: 'user_id', dependent: :destroy
  has_many :expenses, foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource

  def index
    @group = current_user.groups.find(params[:group_id])
    @expenses = @group.expenses
    @total = @group.expenses.sum(:amount)
  end

  def new
    @expense = Expense.new
    @current_user = current_user
    @group = Group.find(params[:group_id])
  end

  def create
    @group = Group.find(params[:group_id])
    @expense = @group.expenses.create(name: expense_params[:name], amount: expense_params[:amount],
                                      user_id: current_user.id, group_id: @group.id)
    respond_to do |format|
      if @expense.save
        format.html do
          redirect_to user_group_expenses_path(current_user, params[:group_id]),
                      notice: 'Transaction has been successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    @group = set_group
    respond_to do |format|
      format.html do
        redirect_to user_group_expenses_path(current_user, @group.id), notice: 'Budget has been successfully removed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[destroy]
  def index
    if user_signed_in?
      @user = current_user
      @groups = @user.groups.order('created_at DESC')
      @expenses = current_user.expenses
    else
      render root_path
    end
  end

  def new
    @user = User.find(params[:user_id])
    @group = Group.new
  end

  def create
    puts group_params
    @user = User.find(params[:user_id])
    @group = Group.new(group_params)
    @group.user_id = @user.id
    if @group.valid?
      @group.save
      flash[:notice] = 'New Category Created Successfully'
      redirect_to user_groups_path
    else
      flash[:notice] = 'Input a valid Icon image and Name.'
      render :new
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_path, notice: 'Group has been successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_expense.html.erb
<div class="expense-display card mt-3 shadow p-3 mb-5 bg-body rounded w-10">
    <div class="expense-display list-group  card d-flex  p-3 w-10 gap-10">
      <h6 class="card-title">Name: <%= expense.name %></h6>
      <h6 class="card-title">Amount: <%= number_to_currency(expense.amount) %></h6>
      <div class="d-flex gap-4">
        <%= button_to "Delete budget", user_group_expense_path(current_user, @group, expense), method: :delete, class: 'btn btn-secondary p-2' %>
      </div>
    </div> 
</div>

app/views/expenses/index.html.erb
<div class="container">
  <div class="expense-head">
     <h1> <%= link_to user_groups_path do %>
        <i class="fa fa-arrow-left" style="color: #372948; padding-left: 22px"> </i>
        <% end %>
     </h1>
  </div>
  <h2 class="d-flex justify-content-center align-items-center expense-title">Transactions</h1>
  <% if @expenses.count > 0 %>
  <div class="card p-2">
    <div class="expense-total">
      <h4>Total Amount Budget:</h4>
      <h4> <%= number_to_currency(@expenses.sum(&:amount)) %> </h4>
    </div>
    <div class="card-body">
      <div class="d-flex ms-5 mb-3 gap-5 align-items-center icon-card">
        <img src="#{<%= @group.icon %>}", alt="group_icon" class="card-img">
        <h2> <%= @group.name %> </h2>
      </div>
      <% @expenses.each do |expense| %>
        <%= render expense %>
      <% end %>
    </div>
  <% end %>
  <div class="add-group-btn">
    <div class="group-btn shadow p-3 mb-5 rounded">
      <%= link_to "Add Transaction", new_user_group_expense_path(current_user), class: "new-group-btn text-light" %>
    </div>
  </div>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center">
  <div class="expense-header w-100">
    <h1>
      <%= link_to user_group_expenses_path(@current_user, @group) do %>
        <i class="fa fa-arrow-left" style="color: #372948; padding-left: 22px;"> </i>
      <% end %>
    </h1>
  </div>
  <div class="card w-100 d-flex justify-content-center align-items-center  p-3 shadow p-3 mb-5 bg-body rounded">
    <h4 class="expense-title">Details</h4>
    <%= form_with model: @expense, url: user_group_expenses_path(current_user, @group), method: :post, scope: :expense,  class: 'd-flex flex-column  col-md-5 justify-content-center align-items-center' do |f| %> 
      <div class="input-group p-2 mb-3">
        <%= f.label :name, class: "input-group-text" %><br />
        <%= f.text_field :name,  autofocus: true, autocomplete: "name", class: 'form-control' %>
      </div>

      <div class="input-group p-2 mb-3">
        <%= f.label :amount, class: "input-group-text" %><br />
        <%= f.number_field :amount, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "Save Transaction", class: 'btn save-btn'%>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="total">
      <h3> Budget:</h3>
      <h3> <%= number_to_currency(@expenses.sum(&:amount)) %> </h3>
  </div>
  <% if @groups.count > 0 %>
    <% @groups.each do |group|%>
      <div class="card mb-4 px-3 p-3 shadow p-3 mb-5 bg-body rounded">
        <%= link_to user_group_expenses_path(current_user, group.id), class: "text-decoration-none" do %>
          <div class="d-flex">
            <img src="#{<%= group.icon %>}", width="100", height="100", alt="group_icon", class: ' me-3 p-3 border border-white rounded-circle' >        
            <div class="card-title ms-5 d-flex justify-content-between w-100">
              <div>
                
                  <h3 class="border border-white rounded-3"> <%= group.name %></h3>
                
                <span> <%= group.created_at.strftime("%B, %e at %H:%M") %> </span>
              </div>
                <div class="d-flex flex-column justify-content-between align-items-between gap-10">
                  <span class="each-group-amount">$<%= group.expenses.sum(&:amount) %></span>
                  <%= button_to "Delete Group", user_group_path(current_user, group), method: :delete, class: 'btn btn-secondary p-2' %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
  <% end %>
  <div class='add-group-btn'>
    <div class='group-btn shadow p-3 mb-5 rounded'>
      <%= link_to "Add Category", new_user_group_path(current_user), class: 'new-group-btn text-light' %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class=" container d-flex flex-column justify-content-center align-items-center">
  <div class="budget-header w-100">
  <h1> <%= link_to user_groups_path do %>
    <i class="fa fa-arrow-left" aria-hidden="true" style="color: #372948; padding-left: 22px"> </i>
    <% end %>
    </h1>
  </div>
  <div class="card w-100 d-flex justify-content-center align-items-center  p-3 shadow p-3 mb-5 bg-body rounded">
    <h4 class=" d-flex p-2  mb-3">Details</h4>

    <%= form_with model: @group, url: user_groups_path(current_user),  scope: :group, class: 'd-flex flex-column  col-md-5 justify-content-center align-items-center' do |f| %>
      <div class="input-group p-2  mb-3">
        <%= f.label :icon, class: "input-group-text" %><br />
        <%= f.text_field :icon, autofocus: true, autocomplete: "icon", class: 'form-control' %>
      </div>

      <div class="input-group p-2 mb-3">
        <%= f.label :name, class: "input-group-text" %><br />
        <%= f.text_field :name, autocomplete: "name", class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "Save Category", class: 'btn save-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md header__nav">
      <div class="container-fluid">
        <button class="navbar-toggler btn btn-outline-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"><i class="fa fa-bars" aria-hidden="true"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
            <li class="nav-item">
              <span class="nav-link me-5 text-light"><i class="fa fa-user me-2"></i><%= current_user.name %></span>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-warning mt-2" %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: 'nav-link text-light' %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% if notice %>
      <p class="alert alert-info position-absolute top-10 start-50 translate-middle" role="alert"><%= notice %>
         <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
      </p>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger mt-4 position-absolute top-10 start-50 translate-middle" role="alert"><%= alert %>
         <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://kit.fontawesome.com/b331332bf9.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/index.html.erb
<div class="d-flex flex-column justify-content-center min-vh-100 border align-items-center">
  <h1 class="user-head">BUDGET APP</h1>

  <div class="text-center border-secondary">
    <h2 class="app__name">Budgetly</h2>
    <p class="app__description"> Your Ultimate Budgeting tool!</p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-primary w-100 fs-5 login-btn" %>
    <p class="para"> 
    <%= link_to "Sign up", new_user_registration_path, class: "sign_up" %>
    </p>    
  </div>
</div>